# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_distC <- function(X) {
    .Call(`_hhfields_calc_distC`, X)
}

calc_distXYC <- function(X, Y) {
    .Call(`_hhfields_calc_distXYC`, X, Y)
}

